language: go

go:
  - 1.11.x

addons:
  sonarcloud:
    organization: "aarontraas-github"
    token:
      secure: "AI946hTiAyLMsIESn7xMdAd+IscZq9YBAIn1MA3A8XxAGm/H67W/ivc8Qi/DDseCFPiLySY3NHxjDVNUtugfilslbn3obVk/hPe5IadfiKs6qsCQVEfKCAhHLwn9PEPqu8WVxUEbQJ0yB2jS7G2Dvxp9r4m5mvYwqPYAw0uN12QyNliRjX1G27E6Vd0zjWQh82GSBvQEbkIW6pDZxRwT3TGMlRWSPvbDPet6tB8i2B7FbDiRx5tprxdWynZszcAc/BIr0wsWJAILjXGaOY12VjkubOpmwUzEnXA5RTPjRgjSY9pPOnTPr+H/Ld1aE74F9FWjNtOdQdFD/1TtoisPeYVU4r++iNZqZG5WjaEn5c4p3t7tnN7F9h9RjZJSHpJ8E178HGjd1yPReyoDRDOOQH4EFFsdgvCRbWqS+Gw/6R7mIEX6hhpYeJALJQLULnNt4y/UTBhTYcF7jn5xH8le6lR3fF7CC2okiIHBFXmz6eg+rOLPl4owWHSR9EXeDhZyvrCENZiogLJFq1U4aAfWOAOnGqDTFXEnWRCD/vOsDbfwIliEvXIgpYeJFNJBomOTJXgCwUXL4DwC4UlwXb720xHJNe1MUKNPb8y6aCVcyUmuvrPK7y9Dh4F1/kI213r1OPgrPLEY7LTMHF0By+9+YR7mUAYmQNs3SdSTb0ayL3A="

script:
  - go test -coverprofile=coverage.out
  - sonar-scanner
